# Site settings
title: audrey grace choi
# email:
description: > # this means to ignore newlines until "baseurl:"
  (c) Audrey Grace Choi
baseurl: "/blog"
production_url : http://audreygchoi.github.io.com/blog
url:  # the base hostname & protocol for your site
twitter_username: alwaysaudreygrace
github_username:  audreygchoi

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


# collections:
#   portfolio:
#     output: true
#     permalink: /portfolio/:path/
#   poetry:
#     output: true
#     permalink: /poetry/:path/
#
